name: Duplicate issue report
description: Report an issue or pull request that already exists in the project.
title: "[DUPLICATE]: <Provide a brief title>"
labels: ["duplicate"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please provide information about the duplicate issue or pull request.

  - type: input
    id: duplicate_link
    attributes:
      label: Link to the original issue/pull request
      description: Provide the URL of the original issue or pull request that duplicates this one.
      placeholder: "https://github.com/your-repo/issue/123"

  - type: input
    id: reason
    attributes:
      label: Reason for marking as duplicate
      description: Explain why this issue is considered a duplicate.
      placeholder: "Briefly explain why this is a duplicate."

  - type: input
    id: additional
    attributes:
      label: Additional context
      description: Add any additional context or supporting information.
      placeholder: "Any additional information or comments..."
