name: Good first issue
description: Suitable for newcomers or those new to the project.
title: "[GOOD FIRST ISSUE]: <Provide a descriptive title>"
labels: ["good first issue"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Welcome to contributing to our project! This issue is marked as a "Good First Issue," which means it is a great starting point for new contributors. Please provide the following information to help us understand your issue.

  - type: input
    id: issue_summary
    attributes:
      label: Issue summary
      description: Provide a brief summary of the issue or task.
      placeholder: "Summarize the issue or task..."

  - type: textarea
    id: detailed_description
    attributes:
      label: Detailed description
      description: Provide a detailed description of what needs to be done, including any relevant background information or steps.
      placeholder: "Describe the issue or task in detail, including any relevant information..."

  - type: input
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce (if applicable)
      description: If this issue involves a bug, list the steps to reproduce the problem.
      placeholder: "List the steps to reproduce the issue (if applicable)..."

  - type: input
    id: expected_outcome
    attributes:
      label: Expected outcome
      description: Describe what you expect to happen once the issue is resolved.
      placeholder: "Describe the expected outcome..."

  - type: input
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or information that might be helpful for resolving the issue.
      placeholder: "Any additional information or comments..."
