name: Help wanted
description: Request additional help or attention for an issue that needs extra effort.
title: "[HELP WANTED]: <Provide a descriptive title>"
labels: ["help wanted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        We need additional help with this issue. Please provide as much detail as possible to assist contributors.

  - type: textarea
    id: issue_description
    attributes:
      label: Issue description
      description: Provide a detailed description of the issue and what kind of help is needed.
      placeholder: "Describe the issue and the type of help required..."

  - type: input
    id: specific_tasks
    attributes:
      label: Specific tasks
      description: List any specific tasks or sub-tasks where help is needed.
      placeholder: "List specific tasks or areas where help is needed..."

  - type: input
    id: additional_resources
    attributes:
      label: Additional resources
      description: Provide links to related documentation, resources, or references that might help contributors.
      placeholder: "Link to relevant resources or documentation..."

  - type: input
    id: additional
    attributes:
      label: Additional context
      description: Add any extra information or context that might help in addressing the issue.
      placeholder: "Any additional information or comments..."
