name: Invalid issue report
description: Report an issue that doesn't seem correct or is invalid.
title: "[INVALID]: <Provide a brief title>"
labels: ["invalid"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        If you've identified an issue that seems incorrect or should not exist, please fill out the form below to provide more details.

  - type: input
    id: reason
    attributes:
      label: Reason for invalidation
      description: Briefly explain why this issue is considered invalid or incorrect.
      placeholder: "Why do you think this issue is invalid?"

  - type: textarea
    id: steps
    attributes:
      label: Steps to validate
      description: Provide steps or evidence that confirm the issue is invalid.
      placeholder: "Explain how you verified this issue is not valid..."

  - type: input
    id: original_issue
    attributes:
      label: Related issue (if applicable)
      description: Provide a link to the original issue if this is related to an existing one.
      placeholder: "Link to the related issue (if applicable)"

  - type: input
    id: additional
    attributes:
      label: Additional context
      description: Any additional information you think is necessary.
      placeholder: "Add any other context here..."
