name: Question or Information Request
description: Ask a question or request more information related to the project.
title: "[QUESTION]: <Provide a short title>"
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form below to ask your question or request further information.

  - type: input
    id: question_summary
    attributes:
      label: Summary of your question
      description: Provide a brief summary of your question or information request.
      placeholder: "Summarize your question in a few words..."

  - type: textarea
    id: question_details
    attributes:
      label: Question details
      description: Provide a detailed explanation of your question or what information you're requesting.
      placeholder: "Describe your question or information request in detail..."

  - type: input
    id: context
    attributes:
      label: Context for the question
      description: Provide any relevant context or background information that may help clarify your question.
      placeholder: "Add context for your question (e.g., where you encountered the issue, what you're trying to do)..."

  - type: input
    id: additional
    attributes:
      label: Additional context
      description: Add any additional information that may help answer your question.
      placeholder: "Any extra information or comments..."
