name: Won't fix
description: Mark an issue as won't fix if it will not be addressed or resolved.
title: "[WONTFIX]: <Provide a brief title>"
labels: ["wontfix"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        This issue will not be fixed. Please provide reasons or context for why the issue is being closed as won't fix.

  - type: textarea
    id: reason
    attributes:
      label: Reason for won't fix
      description: Explain why this issue will not be fixed or addressed.
      placeholder: "Describe the reason why this issue is being marked as won't fix..."

  - type: input
    id: decision_maker
    attributes:
      label: Decision maker
      description: Specify who made the decision to mark the issue as won't fix.
      placeholder: "Name of the person or team responsible for this decision..."

  - type: input
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or information relevant to the decision.
      placeholder: "Any additional information or comments..."
